#! /bin/bash
if [[ -n $1 ]]
then
	if [[ "${1:0-1}" == "/" ]]
	then
		scandir=$1*
	else
		scandir=$1/*
	fi
else
	scandir=./*
fi

sudo du -s $scandir |sort -nr |head -30 |awk '{printf("%0.fM\t%s %s\n", $1/2048, $2, $3)}'
